export const GET_PROFILE="GET_PROFILE";
export const GET_PROFILES="GET_PROFILES";
export const GET_REPOS="GET_REPOS";
export const  PROFILE_ERROR="PROFILE_ERROR";
export const CLEAR_PROFILE="CLEAR_POFILE"
export const UPDATE_PROFILE="UPDATE_PROFILE"
export const ACCOUNT_DELETED="ACCOUNT_DELETED"
